<ul id="sidenav">
	<li><a href="<?=$this->url(array('controller'=>'index', 'action' => 'index'))?>">Home</a></li>
	<li><a href="<?=$this->url(array('controller'=>'queue', 'action' => 'index'))?>">Queue Status</a></li>
	<li><a href="<?=$this->url(array('controller'=>'config', 'action' => 'index'))?>">Image Configuration</a></li>
    <li><a href="<?=$this->url(array('controller'=>'network-config', 'action' => 'index'))?>">Network Configuration</a></li>
    <li><a href="<?=$this->url(array('controller'=>'alert-config', 'action' => 'index'))?>">Alert Configuration</a></li>
    <li><a href="<?=$this->url(array('controller'=>'error-log', 'action' => 'index'))?>">Error Log</a></li>
</ul>
