<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html>
<head>
	<title>Novarad DICOM Router Configuration</title>
	<link rel="stylesheet" href="/css/style.css" />
    <script src="/js/jquery-1.6.2.min.js"></script>
    <script src="/js/script.js"></script>
</head>
<body>
<h1>Novarad DICOM Router Configuration</h1>

<?php echo $this->partial('sidenav.phtml'); ?>

<div role="main" id="content">
<?php echo $this->layout()->content; ?>
</div>

</body>
</html>
